import './globals.scss'
import Header from '@/components/organisms/Header/Header'
import Footer from '@/components/organisms/Footer/Footer'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Brasserie',
  description: 'Generated by create next app',
}


const links=[
  {
    href: "/#home",
    children: "accueil",
  },
  {
    href: "/#new",
    children: "nouveauté",
  },
  {
    href: "/#test",
    children: "test",
  },
]

const logo = {
  src: "https://picsum.photos/200/300",
  alt: 'logo du site',
}

export default function RootLayout({children } : {children: React.ReactNode}) {
  return (
    <html lang="fr">
      <body className={inter.className}>
        <Header 
          logo={logo}
          links={links}
        />
        {children}
        <Footer 
          logo={logo}
        />
      </body>
    </html>
  )
}
